### ISSUE TITLE
sctransform pipeline?

### ISSUE THREAD

**Issue by kurchejs** [EDePasquale/DoubletDecon#13]
Hey all, 

Wondering if anyone can help me with this error after Main_Doublet_Decon:

**Error in (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA,  :  no locations are finite**

I used the sctransform pipeline in Seurat to generate my Surat data object ("integrated") followed by:

singlets<-Improved_Seurat_Pre_Process(integrated, num_genes = 50, write_files = FALSE)

I was able to generate appropriate tables from the "singlets" file:
#Save tables
write.table(singlets$newExpressionFile, file="singlets_Expression.txt",sep="\t")
write.table(singlets$newFullExpressionFile,file="singlets_newFullExpression.txt",sep="\t")
write.table(singlets$newGroupsFile, file="singlets_newGroups.txt",sep="\t",col.names = F)

But got the convergence error from the following:
results<-Main_Doublet_Decon(rawDataFile = singlets$newExpressionFile, groupsFile = singlets$newGroupsFile, filename="deconvoluted.txt", location="C:/Users/kurchejs/Desktop/WorkingII/SingleNuclei_RNAseq/YanHu")
Loading packages...
Reading data...
Processing raw data...
Creating original data heatmap...
Combining similar clusters...
**Error in (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA,  :  no locations are finite**

Thanks!

**Comment by EDePasquale** [comment]
Hi,

This error most commonly occurs when the rhop value you selected causes too much or too little merging of the clusters, leading to an error in the Markov clustering portion of the algorithm. Which rhop value are you using? The DoubletDecon UI has a built in function for displaying all possible values of rhop to make it easier to choose one within in the range, but this can be done manually as well. Generally I will try multiple values (i.e. 0.9, 1, 1.1, etc.) around 1 until I hit on one that shows the Markov clustering heatmap. From there you can evaluate the appropriateness of the clustering and adjust up or down depending on whether you want less or more cluster merging, respectively. Please let me know if this doesn't solve your problem or if you would like more guidance on running the software.

Thanks!
Erica

**Comment by kurchejs** [comment]
Thanks, Erica. I was able to get it to work, albeit at a low rho - 0.6.

**Comment by EDePasquale** [comment]
Good, I'm glad that worked for you! The rhop value is actually a calculated cutoff of rhop*SD +/- the mean correlation value, not the correlation (rho) itself. This was done to try to keep the range of rhop values small and fairly equivalent between datasets, regardless of the degree of cluster similarity, but could use some more tweaking to make it more intuitive.
