### ISSUE TITLE
Running DoubletDecon on integrated seurat objects

### ISSUE THREAD

**Issue by saisomesh2594** [EDePasquale/DoubletDecon#15]
Hello,

I was wondering if it is a good practice to run DoubletDecon on an integrated seurat object (multiple samples) or would you recommend to run DoubletDecon on seurat objects of individual samples and then remove putative doublets and then do the integration ?

Thanks,
Somesh

**Comment by Tushar-87** [comment]
> Hello,
> 
> I was wondering if it is a good practice to run DoubletDecon on an integrated seurat object (multiple samples) or would you recommend to run DoubletDecon on seurat objects of individual samples and then remove putative doublets and then do the integration ?
> 
> Thanks,
> Somesh

Hello,

The following link sheds some light:

https://github.com/satijalab/seurat/issues/1814

I think it makes sense to run DoubletDecon on individual samples first and then try to integrate.

Best wishes,
Tushar

**Comment by EDePasquale** [comment]
Thank you for the question Somesh and thanks for the response Tushar, you are correct!

We suggest running any doublet removal tool, including DoubletDecon, on each sample first before integration.

Best,
Erica
