### ISSUE TITLE
Eagerly waiting for the protocol or guided tutorial...

### ISSUE THREAD

**Issue by Tushar-87** [EDePasquale/DoubletDecon#16]
Dear Developers,

Thanks a lot for providing this tool. I understand it is an early phase in its usage.
Your Cell Report paper and github page have helped to understand how the tool would work. 
However, these are not sufficient for new users.
It would be really helpful if you could provide a guided tutorial as in case of Seurat.

With gratitude,
Tushar

**Comment by EDePasquale** [comment]
Hi Tushar,

Thanks for reaching out with the suggestion. We understand that running DoubletDecon can be a little difficult when you are first using it, so we are currently preparing a protocol for using the method (including with Seurat) that we are trying to make available ASAP. Stay tuned for more details!

Thanks,
Erica

**Comment by Tushar-87** [comment]
> Hi Tushar,
> 
> Thanks for reaching out with the suggestion. We understand that running DoubletDecon can be a little difficult when you are first using it, so we are currently preparing a protocol for using the method (including with Seurat) that we are trying to make available ASAP. Stay tuned for more details!
> 
> Thanks,
> Erica

thank you Erica.
