### ISSUE TITLE
issue at step: "combining similar clusters"

### ISSUE THREAD

**Issue by drhochbaum** [EDePasquale/DoubletDecon#2]
I think I have successfully pre-processed my data from Seurat using the Seurat_Pre_Process function, but I can't seem to run the Main_Doublet_Decon: 

[1] "Reading data..."
[1] "Processing raw data..."
[1] "Combining similar clusters..."
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 2
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘as.color’

Im not sure if the as.color package not being available is causing this issue? (as.color is no longer available for current R version 3.5.1)?

Any help will be much appreciated!
Best
Daniel

**Comment by catsargent** [comment]
Hi Daniel, 

I also had the same error message. I managed to get around it by downloading the archived version of as.color from here:
https://cran.r-project.org/src/contrib/Archive/as.color/

and then installing it from source:
install.packages("~/Downloads/as.color_0.1.tar.gz", repos = NULL, type="source")

Regards,
Catherine
