### ISSUE TITLE
Creating synthetic doublets error

### ISSUE THREAD

**Issue by xnnba** [EDePasquale/DoubletDecon#21]
Dear Author,

I got the following error in the creating synthetic doublets step:

Creating synthetic doublet profiles...
Error in weighted.mean.default(newX[, i], ...) : 
  'x' and 'w' must have the same length

Can you help fix that? Thank you!

**Comment by EDePasquale** [comment]
Hi xnnba,

Thank you for writing in, I'll try to get to the bottom of this as soon as possible. Could you please include the log file generated for this experiment, this will give me an idea of how it interpreted the input? Additionally, knowing what line of code produced the error and the dimensions/types of inputs for the Main_Doublet_Decon() function would be extremely helpful. As it stands, while I know the error occurs in the synthetic doublet generation function at the point of calculating the weighted mean, I don't know what input is causing the problem. 

Best,
Erica

**Comment by drneavin** [comment]
Hi Erica,

I am also having this issue, please let me know if you have solved this issue? Here is the output from my file:
```filename: DoubletDecon_results.txt
location: ./
removeCC: FALSE
species: hsa
rhop: 1
write: TRUE
PMF: TRUE
useFull: FALSE
heatmap: TRUE
centroids: TRUE
filename: DoubletDecon_results.txt
location: ./
removeCC: FALSE
species: hsa
rhop: 1
write: TRUE
PMF: TRUE
useFull: FALSE
heatmap: TRUE
centroids: TRUE
num_doubs: 888.49476
only50: FALSE
min_uniq: 4
Reading data...
Processing raw data...
9425 samples after processing
270 genes after processing
Creating original data heatmap...
Combining similar clusters...
filename: DoubletDecon_results.txt
location: ./
removeCC: FALSE
species: hsa
rhop: 0.5
write: TRUE
PMF: TRUE
useFull: FALSE
heatmap: TRUE
centroids: TRUE
num_doubs: 888.49476
only50: FALSE
min_uniq: 4
Reading data...
Processing raw data...
9425 samples after processing
270 genes after processing
Creating original data heatmap...
Combining similar clusters...
New blacklisted clusters: 17, 15, 9, 13, 2-14-6-3-8-16-4-11-12-10-5-7
Creating synthetic doublet profiles...```

Thanks!

-Drew

**Comment by drneavin** [comment]
**Update**: I have also noticed that after I've run `Main_Doublet_Decon` that all of my variables appear to be empty? For example if I type "processed" which was the output of `Improved_Seurat_Pre_Process()`, nothing is returned after running `Main_Doublet_Decon` but it did return the entire contents before running. However it doesn't say "object not found" either. I hope that this may help identify the issue at hand. Also, I am using Seurat - not sure if that is also contributing.

**Comment by drneavin** [comment]
Ok, I have solved the issue. This error results when you are not putting a round number in to the number of doublets for `num_doubs`. I was calculating a proportion based on the total number of cells and resulted in a decimal. A more descriptive error would help the user or by using `round()` in the code. Hope this at least helps someone else who may have this error.

**Comment by EDePasquale** [comment]
Thanks for finding that out, drneavin! I'll add a check for that in the next version.
