### ISSUE TITLE
Post-DoubletDecon Steps

### ISSUE THREAD

**Issue by nrnatesh** [EDePasquale/DoubletDecon#22]
Hello,

I greatly appreciate this tool for identifying doublets in single-cell RNA Sequencing data. I was wondering how I might convert the output file (i.e. Final_nondoublets_groups) into a new object to perform further analysis on, for example using Seurat. Any ideas?

**Comment by EDePasquale** [comment]
Hi nrnatesh,

The primary outputs of DoubletDecon include a 'groups' file and an expression matrix. The groups file is largely used for ICGS and AltAnalyze operations, but for the purposes of Seurat it is not very helpful. The expression matrix that is titled 'Final_nondoublets_exp' contains the expression for all marker genes from Seurat and the DoubletDecon relabeled cell cluster numbers as an additional cell information row. These cluster numbers will differ from Seurat so they should be discarded for these purposes.

The main point is that DoubletDecon will identify a list of cells that you should remove from your dataset in 'Final_doublets_groups'. If the downstream output you need is an expression matrix with markers, then that is provided. You should be able to take your original Seurat object and remove the cells with these specific identifiers, or better to remove them from the original data and rerun your processing pipelines.

Hopefully this is somewhat helpful, please let me know if you have any more questions.

Best,
Erica
