### ISSUE TITLE
Functions in NAMESPACE not exported

### ISSUE THREAD

**Issue by nlawlor** [EDePasquale/DoubletDecon#23]
Hello, 

Thank you for developing DoubletDecon! I installed your package successfully via 

`devtools::install_github('EDePasquale/DoubletDecon')`

But noticed that no functions were being exported in the NAMESPACE (https://github.com/EDePasquale/DoubletDecon/blob/master/NAMESPACE)

After cloning the package and re-documenting with:

`devtools::document()`

This fixed the issue :) I just wanted to note this in case any one else ran into the same problem

**Comment by EDePasquale** [comment]
ahh, thank you for pointing this out! I had trouble getting the document function to work for this patch and guess I just missed that it wiped the namespace. Will fix asap!

**Comment by nlawlor** [comment]
Happy to help :) and thank you for the quick fix!
