### ISSUE TITLE
line 27 of Seurat_pre_process

### ISSUE THREAD

**Issue by drhochbaum** [EDePasquale/DoubletDecon#3]
I think line 27 of Suerat_Pre_Process is missing a comma?
  expression=expression[as.character(clusters2$X)]

should be
  expression=expression[as.character(clusters2$X),]
?
Worked on my machine when I made this edit.

**Comment by alextamburino** [comment]
Hi, can either of you provide guidance on how to format the txt files from Seurat? (code would be even better) I'm trying to run Seurat_Pre_Process and getting several errors along the way. Thanks, Alex
