### ISSUE TITLE
Improved_Seurat_Pre_Processing()

### ISSUE THREAD

**Issue by yoavhadas** [EDePasquale/DoubletDecon#40]
Hi
Thank you for developing this tool and making it compatible with seurat objects
I try to convert a seurat object to a  ICGS-like object by using the following commands:
obj <- readRDS(file = "seurat.rds")
NewObject=Improved_Seurat_Pre_Process(obj, num_genes=50, write_files=TRUE)

after all the clusters were calculated I get the following error:

   Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: 0

Is there any solution to this problem

Thanks
Yoav Hadas

**Comment by shahrozeabbas** [comment]
I am having the same issue. It seems [line 20](https://github.com/EDePasquale/DoubletDecon/blob/master/R/Improved_Seurat_Pre_Process.R) sets `ident.1` to 0.

**Comment by EDePasquale** [comment]
Hi,

This error occurs when the user has selected Seurat cluster identities (Idents) to anything other than the original Seurat cluster numbers. Examples of this include the cell type assignment or custom defined identifiers. To avoid this for now, please use the original Seurat cluster numbers when using DoubletDecon. This will be corrected in a future update that I am currently working on, which will give you more freedom to choose the slot within the Seurat object for the identities you would like DoubletDecon to use.

Best,
Erica
