### ISSUE TITLE
Minor issue with latest update for Seurat 4

### ISSUE THREAD

**Issue by Dazcam** [EDePasquale/DoubletDecon#43]
Hi Erica,

There is a typo in lines 27-28 of the most recent update to the `Improved_Seurat_Pre_Process()` function. 

In Seurat 4 scaled data is located here `seuratObject@assays[["RNA"]]@scale.data`, whereas the code below is directed to `seuratObject@assays[["RNA"]]@scaled.data`.

```R
    #extract expression file
    if(data_type=="counts"){
      expression=as.data.frame(seuratObject@assays[["RNA"]]@counts)
    }else if(data_type=="data"){
      expression=as.data.frame(seuratObject@assays[["RNA"]]@data)
    }else if(data_type=="scaled.data"){
      expression=as.data.frame(seuratObject@assays[["RNA"]]@scaled.data)
    }
```

Otherwise the new updates work well.

Best,

Darren

**Comment by EDePasquale** [comment]
Oops! Fixed now. Thanks, Darren!
