### ISSUE TITLE
problem with example data

### ISSUE THREAD

**Issue by fangling0913** [EDePasquale/DoubletDecon#9]
I tried to run DoubletDecon with the example data to help me understand the tool. However, it always run into problem at the last step. The log was as follows:

Loading packages...
[1] "ERROR: groupsFile must be a character string!"
Reading data...
Processing raw data...
Combining similar clusters...
Creating synthetic doublet profiles...
svd calculated PCA
Importance of component(s):
               PC1   PC2    PC3     PC4     PC5     PC6     PC7    PC8     PC9   PC10    PC11    PC12    PC13    PC14
R2            0.43 0.214 0.1879 0.06106 0.03477 0.01435 0.01032 0.0063 0.00577 0.0051 0.00375 0.00285 0.00212 0.00185
Cumulative R2 0.43 0.644 0.8319 0.89293 0.92770 0.94205 0.95237 0.9587 0.96444 0.9695 0.97329 0.97614 0.97826 0.98011

 Attention: the number of pure cell types = 14  defined in the signature matrix;

 PCA results indicate that the number of cell types in the mixtures = 1 
Step 1: Removing possible doublets...
svd calculated PCA
Importance of component(s):
                 PC1    PC2     PC3     PC4     PC5     PC6     PC7     PC8     PC9    PC10   PC11    PC12    PC13
R2            0.5574 0.1895 0.07032 0.03336 0.02419 0.01826 0.01419 0.01346 0.00841 0.00629 0.0049 0.00432 0.00382
Cumulative R2 0.5574 0.7469 0.81724 0.85060 0.87479 0.89305 0.90724 0.92070 0.92911 0.93540 0.9403 0.94462 0.94844
                 PC14
R2            0.00343
Cumulative R2 0.95187

 Attention: the number of pure cell types = 14  defined in the signature matrix;

 PCA results indicate that the number of cell types in the mixtures = 1 
Step 1: Removing possible doublets...
svd calculated PCA
Importance of component(s):
                 PC1    PC2     PC3     PC4     PC5     PC6     PC7     PC8     PC9    PC10   PC11    PC12    PC13
R2            0.5574 0.1895 0.07032 0.03336 0.02419 0.01826 0.01419 0.01346 0.00841 0.00629 0.0049 0.00432 0.00382
Cumulative R2 0.5574 0.7469 0.81724 0.85060 0.87479 0.89305 0.90724 0.92070 0.92911 0.93540 0.9403 0.94462 0.94844
                 PC14
R2            0.00343
Cumulative R2 0.95187

 Attention: the number of pure cell types = 14  defined in the signature matrix;

 PCA results indicate that the number of cell types in the mixtures = 1 
Step 2: Re-clustering possible doublets...
Step 3: Rescuing cells with unique gene expression...
Error in `colnames<-`(`*tmp*`, value = c("clusterNr", "clusterName", "cellName")) : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning messages:
1: In if (!is.null(v) && is.atomic(x[[jj]]) && !is.null(names(x[[jj]]))) names(x[[jj]]) <- NULL :
  closing unused connection 3 (C:\Users\fangl\Downloads\software\DoubletDecon-master\PBMC_example.log)
2: In reclust_groups$cells <- row.names(reclust_groups) :
  Coercing LHS to a list

Can someone helps me?
Thanks
Linda

**Comment by EDePasquale** [comment]
This issue should be corrected now. Seurat_Pre_Process outputs a matrix but the command line version of DoubletDecon expects a data.frame. The UI version, however, needs a matrix format so I convert to data.frame internally when it is needed in the command line version. Please let me know if this or other problems persist.
